version: '3.5'

services:
  jupyter:
    image: tensorflow/tensorflow:2.3.0-jupyter
    ports:
      - 8888:8888
    container_name: jupyter
    environment:
      NB_UID: 1000
      NB_GID: 100
      GRANT_SUDO: "yes"
      PASSWORD: "password"
      JUPYTER_TOKEN: "token"
    volumes:
      - ../../mnt/:/tf/mnt

  eclipse-theia:
    image: theiaide/theia-python:1.4.0
    ports:
      - 3000:3000
    container_name: eclipse-theia
    volumes:
      - ../../mnt/:/home/project
