apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sample-parameters
spec:
  entrypoint: sample
  arguments:
    parameters:
      - name: datasetpass
        value: ../asset
      - name: mnist-train-images
        value: train-images-idx3-ubyte.gz
      - name: mnist-train-labels
        value: train-labels-idx1-ubyte.gz
      - name: mnist-test-images
        value: t10k-images-idx3-ubyte.gz
      - name: mnist-test-labels
        value: t10k-labels-idx1-ubyte.gz

  templates:
    - name: sample
      inputs:
        parameters:
          - name: datasetpass
          - name: mnist-train-images
          - name: mnist-train-labels
          - name: mnist-test-images
          - name: mnist-test-labels

      container:
        # Execute sample code with input parameters as arguments
        image: aiqmtt/learnsample20
        command:
          - python
          - script.py
        # Set a value for an environment variable
        env:
          - name: PASS
            value: "{{inputs.parameters.datasetpass}}"
          - name: TRAIN-IMAGE
            value: "{{inputs.parameters.mnist-train-images}}"
          - name: TRAIN-LABEL
            value: "{{inputs.parameters.mnist-train-labels}}"
          - name: TEST-IMAGE
            value: "{{inputs.parameters.mnist-test-images}}"
          - name: TEST-LABEL
            value: "{{inputs.parameters.mnist-test-labels}}"
        # 【Will not use】Printing from python with command line arguments for testing arguments
        args:
          # For debugging
          - "$(PASS)"
          - "$(TRAIN-IMAGE)"
          - "$(TRAIN-LABEL)"
          - "$(TEST-IMAGE)"
          - "$(TEST-LABEL)"
        volumeMounts:
          - name: asset
            mountPath: /asset
      volumes:
        - name: asset
          hostPath:
            # Change this to the material location directory for each user
            path: /vagrant
            type: Directory