version: '3.5'

services:
  jupyter:
    build:
      context: ./jupyter
      dockerfile: dockerfile
    ports:
      - 8888:8888
    container_name: jupyter
    environment:
      TZ: Asia/Tokyo
      NB_UID: 1000
      NB_GID: 100
      GRANT_SUDO: "yes"
      PASSWORD: "password"
      JUPYTER_TOKEN: "token"
    volumes:
      - ../../exp/:/workdir/exp
      - ../../data/:/workdir/data
      - ../../test/:/workdir/test

  eclipse-theia:
    image: theiaide/theia-python:1.4.0
    ports:
      - 3000:3000
    container_name: eclipse-theia
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ../../dev/:/home/project/dev
      - ../../local_qai:/usr/local/qai
      - ../TheiaTools:/home/project/TheiaTools
      - ../TheiaTools/.theia:/home/project/.theia
